dist: trusty
sudo: required
services: docker
language: python
python:
- 2.7
script:
- ". ./compare_version.sh"
- ". ./build.sh"
branches:
  only:
  - master
env:
  global:
  - GITHUB_USER: aurbot-user
  - GITHUB_REPO: git@github.com
  - GITHUB_USER_NAME: aurbot
  - GITHUB_USER_EMAIL: aurbot@jankoppe.de
  - GITHUB_REF: github.com/aurbot/aurbot.github.io
  - AURBOT_REF: github.com/aurbot/aurbot
  - secure: L7R+AxvApKLkzQ9/lyVcasxtvbSslFf32mNlMyGIu815j41iykRMfwp6PtmqdhVD5jrYcPeEVeaqtlstssT1YYqEtZa4IGct3J8t75qk3HRKRhVaHi9XEnYa14t/JodInyML9A0mFvdZsLDsuDbsfjcTOO7cezMHgbVwAFFq+TmkAgid4+ejUkqdbfA/sv4xwGPMEjyGcNiaesWVItijUFb+P2UHSYpB8yiQJquVeq+Ad7qTKeogr2YTLZhk219QXprmwtYY1sjLE1WA4Nk30anP/YcbtlDodgSrUMFJd0WwDSCKZ8UhLa/3bbNxbZnDXuXaQ7u4grHqovSJsFzL0ozC3u0fQ1W/sDvDIUFCDPeZHqi+WuZubiCsY7XT0yz6QOWgXG38HRRQ8uuOLiQuVv4tbQBY4sR4oHq2aCoKyW9n5YBFcjk95VeiJQhbou49PCy9vSzN70K6k2Afy66jBt98Qas2NzkniC9/yM6vLcG2G52WT59tPDVYt0flZ2aE0KwYK7K1IFFGL6miNGf94WSedl6NxMIuT6nef5xC2YuQfyV7v7e3chcchMp6ak1xzB6MFyHqaCx6jlrMEqEo3+YY7gIaJgTjSGbnNT5IrbbCSOYUJ8/vsC2idWWKftusahRg4ZrfAhpbxkOlzaKr3l7Szzi0uKZIL+FBpJqptPA=
  matrix:
  - PACKAGE=__compare__
