dist: trusty
sudo: required
services: docker
language: python
python:
  - 2.7
script:
  - ". ./compare_version.sh"
  - ". ./build.sh"
branches:
  only:
    - master
env:
  global:
    - secure: AZPhlxzsbTC2gkMWBtwmxjMo6fbes9w4CuKU2maEXFB04a52RsHEo0LSbfC36B+TeCmZkI2cUgSDfrF5CWLxubUkys/leZpvsILGumNY7v+pqTka7sB2c9i8lLdgeTARbY5w2zUUQnDUQKObIzPa6bqLW6gPjFubhCdOlQUYmFvBmTPHBU3FiPJQyNQheHDU5BUg7Tuh+VbVhh4khVpftBz7vntXYG9Pd0pwoSy0tLBd3hHcWvCxUhyXQk9TLLaGFUHE5u99dn8kmkgoqoyZwK619ZFpUiJIKKtmaaQdStMQhJ7GOA/S4yIOjJmBypcDddUortglK0Naf3z6cshF3y7+Lt3Qpp1UrJYILlTwdjkh00njN0j9g7bKh7+w9ydH6vV1e2+mALRnWwY/NW3mX7UxLDQpm5eD9Xb+oX3zPZfPRnMY3r6BiHubWO2wtdeCIIcaWwQXTwhRkLsBT8rPZ/0HtvdsVJXYc5sAcdB2luF2p+/Hjroj3XUa8/3kukQHhxsvN7bijI6f0ygUiUbrtXJmxVVIe8v5tHQd7WbmPCTbfldKK8lKDNSclEURse1UbHV1i6bXXJOpQjVwYYR7XadlaL2A7HrrhnodRAoRABS/diwXlT8ple3O/5kubZ8qHTLdh5PwGzRtMJX9bNt+T+Wr3dxUrQgofZfzK1OCILA=
    - GITHUB_USER: aurbot-user
    - GITHUB_REPO: git@github.com
    - GITHUB_USER_NAME: "aurbot"
    - GITHUB_USER_EMAIL: aurbot@jankoppe.de
    - GITHUB_REF: github.com/aurbot/aurbot.github.io
    - AURBOT_REF: github.com/aurbot/aurbot
  matrix:
    - PACKAGE=telegram-desktop
    - PACKAGE=__compare__
