dist: trusty
sudo: required
services: docker
language: python
python:
  - 2.7
script:
  - ". ./compare_version.sh"
  - ". ./build.sh"
branches:
  only:
    - master
env:
  global:
    - secure: ladb2E9T9KJmr4xQAIvva09o5LYkKmFMP5uWo4Jzhix52FTywJRORrlKZp3ppeocpaUPUio8RgBf0IUH56sD0QnVDTEFssCsboOruzVQ/HEFSJ70PP3kmwc0kNlKS1ppqEbUxbbvdB7X6r7s9QcpmU6tfjmba23KuIXF+X0BqnXNZg6l2DEWBE1w9O7neT1urerp30cDI/ax7syPSOF6VvfPFcZwHT8Nv5uRAhSoVrKbMNdI9Ex8kUJ4zI7vo3Y28BopjzRPGyHWVleorTUF2kygA9bquYP33ZrFWKw6FMKQtBtpQtYFKFrf0RLFFCOzbInLrvh+f7fRjf0yJtat5DAWmW7cSxIrSzTHxr8xDVCkuzXK2FMxpSp7AN68MDKIMbCtsWxtpbTMvne8U4OmgSFcUMVwR2ezv7u6P+Kv/oasDzi6hUDbXJ/TTbJOnGvy7AAeBZLWtofWxzSCUSX464Wn2g+Xl8IsAE41aFGnRK5ytqNy9LMq8toz2gGC4tv+iIi61vCQTQZCArODvA2L/bTWJdmx6zd6eX22S6zPA1/sy002+Geo3X1oPgvxS+nC5xbnXcFBT2+p/hiVzEvB6kNo0eSUlxj7D1LfQqfUHly6evn5yJ/vV2Mzi1EM03U/cj8ihdq3KMqDsF47H8d0ojqHBtyvU2EEvQ1UyD7HWkg=
    - secure: "wGs59ZzCRkweoWVGhhZ3uxxpYQoAuAyEr1X9RlDTx9JcYtDeV19c+Nj+jUIlpty2yDuhT/dwqXGDmgCETv7D5BaY+OSiezZOLBaU+YLqB7p6kKptENW7Y8yMJAZGUI6KuWnqg+MNSJAQoF+VoIr7gmDU+HNJpR9neM4JPeepbXNch0hTfq9OfqA5hRnBjJ1dV4Q7C7Y79qFlZ/X6UiekA7eJn454ILGB7Hz8MSOM7+iUpB/SDtBl9F/7QNoHSSJ4T72/XLZF3ZTt3kbhvjLmOvVu1UczEuvdALfD/OxXbCZfO3XfSx6XaCVSP6MwX8wcdlvpTtbZnFQcNPvTFRLsXS/oEHQ6aA3nMeQ3bzP4TbaD/dVKOH4c/f/xUzqCWHVjcKIasqmBioYZKzSyaX1b4F15dGfC9O+3gImlTvx+hi4RSPi5zD2z5+qSELlkYfXPbV4x7+uLcj01by+toQAB/cI1t7rEibjpkOirrl7dp96oEDcJjk4zRuODUFQAuXgGzIzOWPSjtWosv1m61eqIoQMbbLQ88tTvlzf73FKRAL6a9v0B7JMQ2ndpJEtHDx57A1d7hIEFJPMNFn8k4AlBNpfOvr/Ivto4lvhDuAcFdL3CAI6pugmxbQTRPrtqM/pV+P75D+aPkcjxF4xLCL/F6DxPsYsuMaVH/89bOAhg/xs="
    - GITHUB_USER: aurbot-user
    - GITHUB_REPO: git@github.com
    - GITHUB_USER_NAME: "aurbot"
    - GITHUB_USER_EMAIL: aurbot@jankoppe.de
    - GITHUB_REF: github.com/aurbot/aurbot.github.io
    - AURBOT_REF: github.com/aurbot/aurbot
  matrix:
    - PACKAGE=__compare__
